#pragma once

enum RenderMode : short {
    SHADOW_MAPPING,
    SHADOW_MAPPING_PCF,
    SSAO,
    SSAO_SHADOW_MAPPING_PCF,
    RAYTRACING_BASE_SHADOWS,
    SURFELS_VISUALIZATION,
    SURFELS_RADIANCE_VISUALIZATION,
    SURFELS_GLOBAL_ILLUMINATION
};
const RenderMode renderConfig = RenderMode::SURFELS_GLOBAL_ILLUMINATION;